export const STATUS_COLORS: Record<string, string> = {
  draft: 'gray',
  pending: 'yellow',
  submitted: 'blue',
  approved: 'green',
  rejected: 'red',
  in_progress: 'blue',
  completed: 'green',
  cancelled: 'gray',
  active: 'green',
  inactive: 'gray',
  open: 'blue',
  closed: 'gray',
  scheduled: 'blue',
  passed: 'green',
  failed: 'red',
  hired: 'green',
  not_hired: 'red',
  online: 'blue',
  onsite: 'purple',
  hybrid: 'orange',
};

export const STATUS_LABELS: Record<string, string> = {
  draft: 'Draft',
  pending: 'Pending',
  submitted: 'Submitted',
  approved: 'Approved',
  rejected: 'Rejected',
  in_progress: 'In Progress',
  completed: 'Completed',
  cancelled: 'Cancelled',
  active: 'Active',
  inactive: 'Inactive',
  open: 'Open',
  closed: 'Closed',
  scheduled: 'Scheduled',
  passed: 'Passed',
  failed: 'Failed',
  hired: 'Hired',
  not_hired: 'Not Hired',
  online: 'Online',
  onsite: 'Onsite',
  hybrid: 'Hybrid',
};
